# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Slots Test App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Slots Test App
  pod 'Then'
  pod 'SwifterSwift/Foundation'
  pod 'SwifterSwift/UIKit'
  pod 'SnapKit', '~> 5.6.0'

end
